/**
 * This file was autogenerated by vite-svg-sprite-compiler plugin.
 * Do not edit this file manually.
 */

/* prettier-ignore */
export type IconName = "arrow-left" | "clipboard-doc-check" | "clipboard-doc" | "close" | "default" | "enter" | "eye-slash" | "eye" | "filter" | "key" | "lock-closed" | "lock-open" | "logout" | "map-pin" | "moon" | "register" | "screen" | "search" | "seat" | "spinner" | "sun";

/* prettier-ignore */
export const spriteInfo = {
  filename: "icons.45f511ca.svg",
  hash: "45f511ca"
} as const;
