/* prettier-ignore */

/**
 * This file was autogenerated by vite-svg-sprite-compiler plugin.
 * Do not edit this file manually.
 */
export type IconName = "arrow-left" | "close" | "default" | "enter" | "eye-slash" | "eye" | "filter" | "key" | "lock-closed" | "lock-open" | "logout" | "map-pin" | "moon" | "register" | "search" | "seat" | "spinner" | "sun";
